# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntas',
            old_name='pregunta',
            new_name='pregunta_texto',
        ),
    ]
